name: Communism
main: com.daytonjwatson.communism.CommunismPlugin
version: 1.0.0
api-version: '1.21'
author: DaytonJWatson
description: A very real plugin that forces players into a centralised "communist" economy.

commands:
  communism:
    description: Manage the communism system.
    usage: "/communism [status|forcepayout|toggle|forcetax|forceinspection|clearpool|givepool|guide|reload]"